<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
    <?=$this->headTitle()?>
	<!--[if lt IE 9]>
	<meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
    <![endif]-->

    <?=$this->headMeta()?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="<?=$this->link('/src/avnpc/css/avnpc.css')?>" media="all" rel="stylesheet" type="text/css" />
    <script src="<?=$this->link('/lib/js/labjs/labjs.min.js')?>"></script>
    <script src="<?=$this->link('/lib/js/jquery/jquery.min.js')?>"></script>
    <script src="<?=$this->link('/lib/js/moment/moment.min.js')?>"></script>

	<link href='http://fonts.googleapis.com/css?family=Sarina|Great+Vibes' rel='stylesheet' type='text/css'>

</head>
<body>

<div id="page">

<!-- #header start-->
<header id="header" class="header">
	<h1><a href="<?=$this->uri('/');?>">Just Fine</a></h1>
	<p>— Story of AlloVince</p>


<nav id="menu">
	<ul class="submenu">
		<li><a href="<?=$this->uri('/'); ?>">Thinking</a></li>
		<li><a href="<?=$this->uri('/life'); ?>">Life</a></li>
		<li><a href="<?=$this->uri('/pages/projects'); ?>">Projects</a></li>
		<li><a href="<?=$this->uri('/pages/about'); ?>">About</a></li>
	</ul>
</nav>

<!-- #header end -->
</header>

<?=$this->content;?>

</div>
</body>
</html>

