<?
if($this->paginator && $this->paginator->getCurrentPageNumber() > 1){
    $this->headTitle('Just Fine - Story of AlloVince | page ' . $this->paginator->getCurrentPageNumber(), 'SET');
} else {
    $this->headTitle('Just Fine - Story of AlloVince', 'SET');
}
?>
<div class="page_content">
    <?if($this->posts):?>
    <div class="vlist posts">
        <?foreach($this->posts as $key => $post):?>
        <div class="item <?=$key == 0 ? 'first' : ''?>">
            <div class="item-inline item_title">
                <h3><a href="<?=$this->uri('/pages/' . $post['urlName'])?>"><?=$post['title']?></a></h2>
                <p class="info">发布时间： <time datetime="<?=$this->datetime()->isoTime($post['createTime'])?>" data-jstime="<?=$this->datetime()->jsTime($post['createTime'])?>" class="agotime"><?=$this->datetime($post['createTime'])?></time></p>
            </div>
        </div>
        <?endforeach;?>
    </div>
    <?if($this->paginator):?>
    <?=$this->paginator->setPath('/')->setBaseQuery($this->query);?>
    <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
    <?endif;?>
    <?endif;?>
</div>
